---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oadp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oadp-operator
  template:
    metadata:
      labels:
        name: oadp-operator
    spec:
      serviceAccountName: oadp-operator
      containers:
        - name: oadp-operator
          # Replace this with the built image name
          image: "quay.io/konveyor/oadp-operator:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "oadp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: REGISTRY
              value: quay.io
            - name: PROJECT
              value: konveyor
            - name: VELERO_REPO
              value: velero
            - name: VELERO_OPENSHIFT_PLUGIN_REPO
              value: openshift-velero-plugin   #TODO: Ask if this needs to be changed or not
            - name: VELERO_RESTIC_RESTORE_HELPER_REPO
              value: velero-restic-restore-helper
            - name: VELERO_AWS_PLUGIN_REPO
              value: velero-plugin-for-aws
            - name: VELERO_GCP_PLUGIN_REPO
              value: velero-plugin-for-gcp
            - name: VELERO_AZURE_PLUGIN_REPO
              value: velero-plugin-for-microsoft-azure
            - name: VELERO_TAG
              value: latest
            - name: VELERO_RESTIC_RESTORE_HELPER_TAG
              value: latest
            - name: VELERO_PLUGIN_TAG
              value: latest
            - name: VELERO_AWS_PLUGIN_TAG
              value: latest
            - name: VELERO_GCP_PLUGIN_TAG
              value: latest
            - name: VELERO_AZURE_PLUGIN_TAG
              value: latest
      volumes:
        - name: runner
          emptyDir: {}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: oadp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: oadp-operator
    namespace: "oadp-operator"
namespace: "oadp-operator"
